name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: vmf_to_stripper
        path: target/${{ matrix.BUILD_TARGET }}/vmf_to_stripper
